name: Docs
on: [push, pull_request, workflow_dispatch]
permissions:
  contents: write
jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install '.[doc]'
      - name: Sphinx build
        run: |
          sphinx-build -b html docs/source docs/build/html
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        # if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/testing' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true
